-- GENERATED by scripts/tests/release-hosted/generate.mjs; synthetic blank staging ONLY.
-- Apply the three unchanged candidate migrations, then 04_hardening.sql before creating accounts.
BEGIN;
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='60s';
-- Fail before any application DDL on a populated or non-managed target.
DO $preflight$ BEGIN
 IF to_regclass('auth.users') IS NULL OR to_regprocedure('auth.uid()') IS NULL
  OR to_regprocedure('auth.jwt()') IS NULL OR to_regclass('auth.identities') IS NULL THEN
  RAISE EXCEPTION 'Managed Supabase Auth is required'; END IF;
 IF EXISTS(SELECT 1 FROM auth.users) THEN RAISE EXCEPTION 'Blank Auth required'; END IF;
 IF EXISTS(SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE n.nspname IN ('public','snap_security','snap_relaunch','snap_billing') AND c.relkind IN ('r','p','v','m','S')) THEN
  RAISE EXCEPTION 'Blank application schemas required'; END IF;
 IF to_regnamespace('snap_security') IS NOT NULL OR to_regnamespace('snap_relaunch') IS NOT NULL
  OR to_regnamespace('snap_billing') IS NOT NULL THEN RAISE EXCEPTION 'Existing application namespace'; END IF;
END $preflight$;

CREATE TABLE public.snap_hosted_fixture (
 singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton),
 kind text NOT NULL CHECK(kind='snap_hosted_synthetic'),
 schema_version integer NOT NULL CHECK(schema_version=1),
 fixture_nonce uuid NOT NULL DEFAULT gen_random_uuid(),
 state text NOT NULL CHECK(state IN ('baseline_only','ready')),
 managed_auth_fingerprint text NOT NULL,
 realtime_fingerprint text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.snap_hosted_fixture ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.snap_hosted_fixture FROM PUBLIC,anon,authenticated,service_role;

-- Definitions only: never copy Auth users, identities, sessions or secrets.
INSERT INTO public.snap_hosted_fixture(kind,schema_version,state,managed_auth_fingerprint,realtime_fingerprint)
SELECT 'snap_hosted_synthetic',1,'baseline_only',
 (SELECT md5(jsonb_agg(to_jsonb(s) ORDER BY kind,name)::text) FROM (
  SELECT 'function' kind,p.oid::regprocedure::text name,pg_get_functiondef(p.oid) definition
  FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='auth' AND p.prokind='f'
  UNION ALL SELECT 'column',a.attname,format_type(a.atttypid,a.atttypmod)||':'||a.attnotnull||':'||coalesce(pg_get_expr(d.adbin,d.adrelid),'')
  FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
  WHERE a.attrelid='auth.users'::regclass AND a.attnum>0 AND NOT a.attisdropped
  UNION ALL SELECT 'constraint',conname,pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid='auth.users'::regclass
 ) s),
 (SELECT md5(jsonb_build_object('publications',
  (SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY pubname),'[]') FROM pg_publication p),
  'tables',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY pubname,schemaname,tablename),'[]') FROM pg_publication_tables t))::text));

CREATE TYPE public.app_role AS ENUM('admin','va','user');
    CREATE TABLE public.user_roles(user_id uuid REFERENCES auth.users(id),role public.app_role,PRIMARY KEY(user_id,role));
    ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
    CREATE POLICY roles_own_read ON public.user_roles FOR SELECT TO authenticated USING(user_id=auth.uid());
    CREATE FUNCTION public.has_role(u uuid,r public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=u AND role=r) $$;
    CREATE TABLE public.user_profiles(user_id uuid UNIQUE REFERENCES auth.users(id),credits integer);
    CREATE TABLE public.foia_profiles(id uuid PRIMARY KEY,role text);

-- Create organizations table
CREATE TABLE public.organizations (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  credits INTEGER DEFAULT 100,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create profiles table for user information
CREATE TABLE public.profiles (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL UNIQUE,
  org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  email TEXT,
  full_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create uploads table for tracking CSV uploads
CREATE TABLE public.uploads (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  filename TEXT NOT NULL,
  size_bytes INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create staging_violations table for raw CSV data
CREATE TABLE public.staging_violations (
  id BIGSERIAL PRIMARY KEY,
  org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  upload_id UUID NOT NULL REFERENCES public.uploads(id) ON DELETE CASCADE,
  raw JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create violations table for processed data
CREATE TABLE public.violations (
  id BIGSERIAL PRIMARY KEY,
  org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  case_id TEXT,
  address TEXT,
  city TEXT,
  state TEXT,
  zip TEXT,
  violation TEXT,
  status TEXT,
  opened_date DATE,
  last_updated DATE,
  snap_score INTEGER DEFAULT 0,
  insight TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create contacts table for skip trace results
CREATE TABLE public.contacts (
  id BIGSERIAL PRIMARY KEY,
  org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  lead_id BIGINT NOT NULL REFERENCES public.violations(id) ON DELETE CASCADE,
  type TEXT NOT NULL, -- 'phone' or 'email'
  value TEXT NOT NULL,
  line_type TEXT,
  is_dnc BOOLEAN DEFAULT false,
  confidence NUMERIC DEFAULT 0,
  source TEXT DEFAULT 'skip_trace',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create audit_events table for tracking actions
CREATE TABLE public.audit_events (
  id BIGSERIAL PRIMARY KEY,
  org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  entity TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable Row Level Security on all tables
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.uploads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staging_violations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.violations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for organizations
CREATE POLICY "Users can view their organization" 
ON public.organizations 
FOR SELECT 
USING (id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "Users can update their organization" 
ON public.organizations 
FOR UPDATE 
USING (id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

-- Create RLS policies for profiles
CREATE POLICY "Users can view their own profile" 
ON public.profiles 
FOR SELECT 
USING (user_id = auth.uid());

CREATE POLICY "Users can insert their own profile" 
ON public.profiles 
FOR INSERT 
WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update their own profile" 
ON public.profiles 
FOR UPDATE 
USING (user_id = auth.uid());

-- Create RLS policies for uploads
CREATE POLICY "Users can view their org uploads" 
ON public.uploads 
FOR SELECT 
USING (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "Users can create uploads for their org" 
ON public.uploads 
FOR INSERT 
WITH CHECK (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "Users can update their org uploads" 
ON public.uploads 
FOR UPDATE 
USING (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

-- Create RLS policies for staging_violations
CREATE POLICY "Users can view their org staging violations" 
ON public.staging_violations 
FOR SELECT 
USING (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "Users can create staging violations for their org" 
ON public.staging_violations 
FOR INSERT 
WITH CHECK (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

-- Create RLS policies for violations
CREATE POLICY "Users can view their org violations" 
ON public.violations 
FOR SELECT 
USING (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "Users can create violations for their org" 
ON public.violations 
FOR INSERT 
WITH CHECK (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "Users can update their org violations" 
ON public.violations 
FOR UPDATE 
USING (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

-- Create RLS policies for contacts
CREATE POLICY "Users can view their org contacts" 
ON public.contacts 
FOR SELECT 
USING (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "Users can create contacts for their org" 
ON public.contacts 
FOR INSERT 
WITH CHECK (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

-- Create RLS policies for audit_events
CREATE POLICY "Users can view their org audit events" 
ON public.audit_events 
FOR SELECT 
USING (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "Users can create audit events for their org" 
ON public.audit_events 
FOR INSERT 
WITH CHECK (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

-- Create function to update timestamps
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

-- Create triggers for automatic timestamp updates
CREATE TRIGGER update_organizations_updated_at
BEFORE UPDATE ON public.organizations
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_profiles_updated_at
BEFORE UPDATE ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_violations_updated_at
BEFORE UPDATE ON public.violations
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Create indexes for better performance
CREATE INDEX idx_profiles_user_id ON public.profiles(user_id);
CREATE INDEX idx_profiles_org_id ON public.profiles(org_id);
CREATE INDEX idx_uploads_org_id ON public.uploads(org_id);
CREATE INDEX idx_staging_violations_org_id ON public.staging_violations(org_id);
CREATE INDEX idx_staging_violations_upload_id ON public.staging_violations(upload_id);
CREATE INDEX idx_violations_org_id ON public.violations(org_id);
CREATE INDEX idx_violations_snap_score ON public.violations(snap_score);
CREATE INDEX idx_violations_city ON public.violations(city);
CREATE INDEX idx_violations_status ON public.violations(status);
CREATE INDEX idx_contacts_org_id ON public.contacts(org_id);
CREATE INDEX idx_contacts_lead_id ON public.contacts(lead_id);
CREATE INDEX idx_audit_events_org_id ON public.audit_events(org_id);

-- Insert demo organization
INSERT INTO public.organizations (id, name, credits) 
VALUES ('00000000-0000-0000-0000-000000000001', 'Demo Organization', 100);

DROP TABLE public.contacts;

CREATE TABLE public.properties(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),address text,city text,state text,zip text);
    ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
    CREATE POLICY held_properties ON public.properties FOR SELECT TO authenticated USING(public.has_role(auth.uid(),'admin'));
    CREATE TABLE public.unlocked_properties(user_id uuid,property_id uuid REFERENCES public.properties(id) ON DELETE CASCADE,PRIMARY KEY(user_id,property_id));
    CREATE FUNCTION public.fn_check_unlocked_batch(p_user_id uuid,p_property_ids uuid[]) RETURNS TABLE(property_id uuid)
      LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ BEGIN
      IF auth.uid() IS NULL OR p_user_id IS DISTINCT FROM auth.uid() THEN RAISE EXCEPTION 'Account access denied' USING ERRCODE='42501'; END IF;
      RETURN QUERY SELECT u.property_id FROM public.unlocked_properties u WHERE user_id=auth.uid() AND u.property_id=ANY(p_property_ids); END $$;

-- User activity tracking
CREATE TABLE lead_activity (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  property_id UUID REFERENCES properties(id) ON DELETE CASCADE,
  user_id UUID,
  status TEXT,
  notes TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Lead lists (collections)
CREATE TABLE lead_lists (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID,
  name TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Junction table for many-to-many
CREATE TABLE list_properties (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  list_id UUID REFERENCES lead_lists(id) ON DELETE CASCADE,
  property_id UUID REFERENCES properties(id) ON DELETE CASCADE,
  added_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(list_id, property_id)
);

-- ============================================================
-- BYOA Phase 1: Owners + Integrations + Vault Encryption + Cron
-- ============================================================

-- ── 1. OWNERS TABLE ─────────────────────────────────────────
create table if not exists public.owners (
  id uuid primary key default gen_random_uuid(),
  property_id uuid not null references public.properties(id) on delete cascade,
  org_id uuid not null references public.organizations(id) on delete cascade,
  name text,
  phones jsonb default '[]'::jsonb,
  emails jsonb default '[]'::jsonb,
  mailing_address text,
  confidence text,
  source text,
  raw_payload jsonb,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_owners_property_id on public.owners(property_id);
create index if not exists idx_owners_org_created on public.owners(org_id, created_at desc);

alter table public.owners enable row level security;

create policy "owners_org_select" on public.owners for select
  using (org_id in (select org_id from public.profiles where user_id = auth.uid()));
create policy "owners_org_insert" on public.owners for insert
  with check (org_id in (select org_id from public.profiles where user_id = auth.uid()));
create policy "owners_org_update" on public.owners for update
  using (org_id in (select org_id from public.profiles where user_id = auth.uid()));
create policy "owners_org_delete" on public.owners for delete
  using (org_id in (select org_id from public.profiles where user_id = auth.uid()));

create trigger trg_owners_updated_at
  before update on public.owners
  for each row execute function public.update_updated_at_column();

-- ── 2. USER_INTEGRATIONS ────────────────────────────────────
create table if not exists public.user_integrations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  org_id uuid not null references public.organizations(id) on delete cascade,
  service_name text not null check (service_name in (
    'twilio','telnyx','batchdata','tracerfy','skipgenie',
    'gohighlevel','hubspot','podio','resimpli','zapier_webhook'
  )),
  vault_secret_id uuid not null,
  display_metadata jsonb not null default '{}'::jsonb,
  status text not null default 'active' check (status in (
    'active','invalid','expired','rate_limited','disabled'
  )),
  last_validated_at timestamptz,
  validation_failure_count int not null default 0,
  daily_spend_cap_usd numeric(8,2),
  daily_spend_used_usd numeric(8,2) not null default 0,
  daily_spend_reset_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (org_id, service_name)
);

alter table public.user_integrations enable row level security;

create policy "user_integrations_org_select" on public.user_integrations for select
  using (org_id in (select org_id from public.profiles where user_id = auth.uid()));
create policy "user_integrations_org_insert" on public.user_integrations for insert
  with check (org_id in (select org_id from public.profiles where user_id = auth.uid()));
create policy "user_integrations_org_update" on public.user_integrations for update
  using (org_id in (select org_id from public.profiles where user_id = auth.uid()));
create policy "user_integrations_org_delete" on public.user_integrations for delete
  using (org_id in (select org_id from public.profiles where user_id = auth.uid()));

create trigger trg_user_integrations_updated_at
  before update on public.user_integrations
  for each row execute function public.update_updated_at_column();

-- ── 3. INTEGRATION_ACTION_LOG ───────────────────────────────
create table if not exists public.integration_action_log (
  id bigserial primary key,
  integration_id uuid references public.user_integrations(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  action_type text not null,
  request_metadata jsonb,
  response_status int,
  success boolean not null,
  error_code text,
  error_message text,
  cost_estimate_usd numeric(8,4),
  created_at timestamptz not null default now()
);

create index if not exists idx_iaction_log_integration_created
  on public.integration_action_log(integration_id, created_at desc);
create index if not exists idx_iaction_log_user_created
  on public.integration_action_log(user_id, created_at desc);

alter table public.integration_action_log enable row level security;

create policy "iaction_log_org_select" on public.integration_action_log for select
  using (
    integration_id in (
      select id from public.user_integrations
      where org_id in (select org_id from public.profiles where user_id = auth.uid())
    )
  );

-- ── 4. SUPPRESSION_LIST ─────────────────────────────────────
create table if not exists public.suppression_list (
  id uuid primary key default gen_random_uuid(),
  phone_number text,
  email text,
  reason text not null,
  added_by uuid references auth.users(id) on delete set null,
  org_id uuid references public.organizations(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists idx_suppression_phone on public.suppression_list(phone_number);
create index if not exists idx_suppression_email on public.suppression_list(email);

alter table public.suppression_list enable row level security;

create policy "suppression_org_select" on public.suppression_list for select
  using (
    org_id is null
    or org_id in (select org_id from public.profiles where user_id = auth.uid())
  );
create policy "suppression_org_insert" on public.suppression_list for insert
  with check (org_id in (select org_id from public.profiles where user_id = auth.uid()));
create policy "suppression_org_update" on public.suppression_list for update
  using (org_id in (select org_id from public.profiles where user_id = auth.uid()));
create policy "suppression_org_delete" on public.suppression_list for delete
  using (org_id in (select org_id from public.profiles where user_id = auth.uid()));

-- ── 5. USER_ACTIVATION_EVENTS ───────────────────────────────
create table if not exists public.user_activation_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  metadata jsonb default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists idx_activation_user_event
  on public.user_activation_events(user_id, event_type, occurred_at desc);

alter table public.user_activation_events enable row level security;

create policy "activation_own_select" on public.user_activation_events for select
  using (user_id = auth.uid());
create policy "activation_own_insert" on public.user_activation_events for insert
  with check (user_id = auth.uid());

-- BYOA Phase 1.5: Add unique constraint on owners(property_id, source)
-- Ensures each skip-trace provider maintains exactly one record per property.
-- Re-runs of the same provider will UPSERT/overwrite instead of accumulating duplicates.

-- First, deduplicate any existing rows (keep newest per property_id+source)
delete from public.owners o
using public.owners o2
where o.property_id = o2.property_id
  and coalesce(o.source, '') = coalesce(o2.source, '')
  and o.created_at < o2.created_at;

-- Backfill null sources to 'unknown' so the unique constraint is enforceable
update public.owners set source = 'unknown' where source is null;

alter table public.owners
  alter column source set not null,
  alter column source set default 'unknown';

create unique index if not exists ux_owners_property_source
  on public.owners(property_id, source);

-- ============================================================
-- Phase 3: Lead Pipeline + CSV Import (Foundation)
-- ============================================================

-- ---------- pipeline_stages ----------
CREATE TABLE public.pipeline_stages (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id      UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  color       TEXT NOT NULL DEFAULT '#64748b',
  is_won      BOOLEAN NOT NULL DEFAULT false,
  is_lost     BOOLEAN NOT NULL DEFAULT false,
  is_default  BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_pipeline_stages_org ON public.pipeline_stages(org_id, sort_order);

ALTER TABLE public.pipeline_stages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "pipeline_stages_org_select"
ON public.pipeline_stages FOR SELECT TO authenticated
USING (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "pipeline_stages_org_insert"
ON public.pipeline_stages FOR INSERT TO authenticated
WITH CHECK (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "pipeline_stages_org_update"
ON public.pipeline_stages FOR UPDATE TO authenticated
USING (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()))
WITH CHECK (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "pipeline_stages_org_delete"
ON public.pipeline_stages FOR DELETE TO authenticated
USING (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));


-- ---------- leads ----------
CREATE TABLE public.leads (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id              UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  property_id         UUID NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
  owner_id            UUID REFERENCES public.owners(id) ON DELETE SET NULL,
  stage_id            UUID NOT NULL REFERENCES public.pipeline_stages(id) ON DELETE RESTRICT,
  assigned_to         UUID,                    -- auth.users.id (no FK to auth schema)
  created_by          UUID NOT NULL,
  priority            INTEGER NOT NULL DEFAULT 0,
  source              TEXT NOT NULL DEFAULT 'manual',
  notes               TEXT,
  last_contacted_at   TIMESTAMPTZ,
  next_follow_up_at   TIMESTAMPTZ,
  archived_at         TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (org_id, property_id)
);

CREATE INDEX idx_leads_org_stage         ON public.leads(org_id, stage_id);
CREATE INDEX idx_leads_assigned_to       ON public.leads(assigned_to);
CREATE INDEX idx_leads_property          ON public.leads(property_id);
CREATE INDEX idx_leads_next_follow_up    ON public.leads(next_follow_up_at) WHERE next_follow_up_at IS NOT NULL;
CREATE INDEX idx_leads_priority          ON public.leads(org_id, priority DESC);

ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

CREATE POLICY "leads_org_select"
ON public.leads FOR SELECT TO authenticated
USING (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "leads_org_insert"
ON public.leads FOR INSERT TO authenticated
WITH CHECK (
  org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid())
  AND created_by = auth.uid()
);

CREATE POLICY "leads_org_update"
ON public.leads FOR UPDATE TO authenticated
USING (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()))
WITH CHECK (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "leads_org_delete"
ON public.leads FOR DELETE TO authenticated
USING (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));


-- ---------- lead_activities ----------
CREATE TABLE public.lead_activities (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id        UUID NOT NULL REFERENCES public.leads(id) ON DELETE CASCADE,
  org_id         UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  actor_id       UUID,                          -- null for system events
  activity_type  TEXT NOT NULL CHECK (activity_type IN
    ('note','call','sms','email','stage_change','distress_event','assignment','task','system')),
  payload        JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_lead_activities_lead ON public.lead_activities(lead_id, created_at DESC);
CREATE INDEX idx_lead_activities_org  ON public.lead_activities(org_id, created_at DESC);
CREATE INDEX idx_lead_activities_type ON public.lead_activities(activity_type);

ALTER TABLE public.lead_activities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "lead_activities_org_select"
ON public.lead_activities FOR SELECT TO authenticated
USING (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "lead_activities_org_insert"
ON public.lead_activities FOR INSERT TO authenticated
WITH CHECK (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "lead_activities_org_delete"
ON public.lead_activities FOR DELETE TO authenticated
USING (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));


-- ---------- lead_tags ----------
CREATE TABLE public.lead_tags (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id      UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  label       TEXT NOT NULL,
  color       TEXT NOT NULL DEFAULT '#64748b',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (org_id, label)
);

ALTER TABLE public.lead_tags ENABLE ROW LEVEL SECURITY;

CREATE POLICY "lead_tags_org_all"
ON public.lead_tags FOR ALL TO authenticated
USING (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()))
WITH CHECK (org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid()));


-- ---------- lead_tag_assignments ----------
CREATE TABLE public.lead_tag_assignments (
  lead_id     UUID NOT NULL REFERENCES public.leads(id) ON DELETE CASCADE,
  tag_id      UUID NOT NULL REFERENCES public.lead_tags(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (lead_id, tag_id)
);

ALTER TABLE public.lead_tag_assignments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "lead_tag_assignments_org_all"
ON public.lead_tag_assignments FOR ALL TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.leads l
    WHERE l.id = lead_tag_assignments.lead_id
      AND l.org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid())
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.leads l
    WHERE l.id = lead_tag_assignments.lead_id
      AND l.org_id IN (SELECT org_id FROM public.profiles WHERE user_id = auth.uid())
  )
);


-- ---------- updated_at triggers ----------
CREATE TRIGGER trg_pipeline_stages_updated_at
BEFORE UPDATE ON public.pipeline_stages
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER trg_leads_updated_at
BEFORE UPDATE ON public.leads
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


-- ---------- Default stage seeder ----------
CREATE OR REPLACE FUNCTION public.seed_default_pipeline_stages(_org_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.pipeline_stages (org_id, name, sort_order, color, is_won, is_lost, is_default)
  VALUES
    (_org_id, 'New',            10, '#3b82f6', false, false, true),
    (_org_id, 'Researching',    20, '#8b5cf6', false, false, true),
    (_org_id, 'Contacted',      30, '#06b6d4', false, false, true),
    (_org_id, 'Negotiating',    40, '#f59e0b', false, false, true),
    (_org_id, 'Under Contract', 50, '#10b981', false, false, true),
    (_org_id, 'Closed Won',     60, '#059669', true,  false, true),
    (_org_id, 'Closed Lost',    70, '#94a3b8', false, true,  true)
  ON CONFLICT DO NOTHING;
END;
$$;

-- Auto-seed stages for new orgs
CREATE OR REPLACE FUNCTION public.handle_new_org_pipeline_stages()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public.seed_default_pipeline_stages(NEW.id);
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_orgs_seed_pipeline_stages
AFTER INSERT ON public.organizations
FOR EACH ROW EXECUTE FUNCTION public.handle_new_org_pipeline_stages();

-- Backfill existing organizations
DO $$
DECLARE
  org_record RECORD;
BEGIN
  FOR org_record IN SELECT id FROM public.organizations LOOP
    PERFORM public.seed_default_pipeline_stages(org_record.id);
  END LOOP;
END $$;


-- ---------- Stage-change activity logger ----------
CREATE OR REPLACE FUNCTION public.log_lead_stage_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'UPDATE' AND OLD.stage_id IS DISTINCT FROM NEW.stage_id THEN
    INSERT INTO public.lead_activities (lead_id, org_id, actor_id, activity_type, payload)
    VALUES (
      NEW.id,
      NEW.org_id,
      auth.uid(),
      'stage_change',
      jsonb_build_object('from_stage_id', OLD.stage_id, 'to_stage_id', NEW.stage_id)
    );
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_leads_log_stage_change
AFTER UPDATE ON public.leads
FOR EACH ROW EXECUTE FUNCTION public.log_lead_stage_change();

-- ============================================================================
-- PHASE 5: SMS + DRIP ENGINE (BYOA Twilio)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. SMS THREADS
-- ----------------------------------------------------------------------------
CREATE TABLE public.sms_threads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  lead_id UUID REFERENCES public.leads(id) ON DELETE SET NULL,
  property_id UUID REFERENCES public.properties(id) ON DELETE SET NULL,
  from_number TEXT NOT NULL,
  to_number TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','paused','closed')),
  last_inbound_at TIMESTAMPTZ,
  last_outbound_at TIMESTAMPTZ,
  last_message_preview TEXT,
  unread_count INTEGER NOT NULL DEFAULT 0,
  created_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (org_id, from_number, to_number)
);
CREATE INDEX idx_sms_threads_org ON public.sms_threads(org_id, updated_at DESC);
CREATE INDEX idx_sms_threads_lead ON public.sms_threads(lead_id);
CREATE INDEX idx_sms_threads_to_number ON public.sms_threads(org_id, to_number);

-- ----------------------------------------------------------------------------
-- 2. SMS MESSAGES
-- ----------------------------------------------------------------------------
CREATE TABLE public.sms_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_id UUID NOT NULL REFERENCES public.sms_threads(id) ON DELETE CASCADE,
  org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  direction TEXT NOT NULL CHECK (direction IN ('outbound','inbound')),
  body TEXT NOT NULL,
  twilio_sid TEXT UNIQUE,
  status TEXT NOT NULL DEFAULT 'queued',
  error_code TEXT,
  cost_cents INTEGER,
  drip_enrollment_id UUID,
  sent_by UUID,
  sent_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_sms_messages_thread ON public.sms_messages(thread_id, sent_at DESC);
CREATE INDEX idx_sms_messages_org ON public.sms_messages(org_id, sent_at DESC);

-- ----------------------------------------------------------------------------
-- 3. DRIP SEQUENCES
-- ----------------------------------------------------------------------------
CREATE TABLE public.drip_sequences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  trigger_type TEXT NOT NULL DEFAULT 'manual' CHECK (trigger_type IN ('manual','stage_change','distress_event')),
  trigger_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_drip_sequences_org ON public.drip_sequences(org_id);

-- ----------------------------------------------------------------------------
-- 4. DRIP STEPS
-- ----------------------------------------------------------------------------
CREATE TABLE public.drip_steps (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sequence_id UUID NOT NULL REFERENCES public.drip_sequences(id) ON DELETE CASCADE,
  step_order INTEGER NOT NULL,
  delay_hours INTEGER NOT NULL DEFAULT 0,
  channel TEXT NOT NULL DEFAULT 'sms' CHECK (channel IN ('sms','email','task')),
  template_body TEXT NOT NULL,
  branch_condition JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (sequence_id, step_order)
);
CREATE INDEX idx_drip_steps_sequence ON public.drip_steps(sequence_id, step_order);

-- ----------------------------------------------------------------------------
-- 5. DRIP ENROLLMENTS
-- ----------------------------------------------------------------------------
CREATE TABLE public.drip_enrollments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  lead_id UUID NOT NULL REFERENCES public.leads(id) ON DELETE CASCADE,
  sequence_id UUID NOT NULL REFERENCES public.drip_sequences(id) ON DELETE CASCADE,
  current_step INTEGER NOT NULL DEFAULT 0,
  next_run_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','paused','completed','cancelled','failed')),
  pause_reason TEXT,
  to_number TEXT,
  enrolled_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  UNIQUE (lead_id, sequence_id)
);
CREATE INDEX idx_drip_enrollments_due ON public.drip_enrollments(next_run_at) WHERE status = 'active';
CREATE INDEX idx_drip_enrollments_org ON public.drip_enrollments(org_id);
CREATE INDEX idx_drip_enrollments_lead ON public.drip_enrollments(lead_id);

-- ----------------------------------------------------------------------------
-- 6. updated_at triggers
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.tg_set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

CREATE TRIGGER tg_sms_threads_updated BEFORE UPDATE ON public.sms_threads
  FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();
CREATE TRIGGER tg_drip_sequences_updated BEFORE UPDATE ON public.drip_sequences
  FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();
CREATE TRIGGER tg_drip_enrollments_updated BEFORE UPDATE ON public.drip_enrollments
  FOR EACH ROW EXECUTE FUNCTION public.tg_set_updated_at();

-- ----------------------------------------------------------------------------
-- 7. RLS — every table org-scoped via profiles.org_id
-- ----------------------------------------------------------------------------
ALTER TABLE public.sms_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sms_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drip_sequences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drip_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drip_enrollments ENABLE ROW LEVEL SECURITY;

-- Helper: current user's org
CREATE OR REPLACE FUNCTION public.current_user_org_id()
RETURNS UUID LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT org_id FROM public.profiles WHERE user_id = auth.uid() LIMIT 1;
$$;

-- sms_threads
CREATE POLICY "org members read sms_threads" ON public.sms_threads
  FOR SELECT USING (org_id = public.current_user_org_id());
CREATE POLICY "org members write sms_threads" ON public.sms_threads
  FOR INSERT WITH CHECK (org_id = public.current_user_org_id());
CREATE POLICY "org members update sms_threads" ON public.sms_threads
  FOR UPDATE USING (org_id = public.current_user_org_id());
CREATE POLICY "admins manage sms_threads" ON public.sms_threads
  FOR ALL USING (public.has_role(auth.uid(), 'admin'));

-- sms_messages
CREATE POLICY "org members read sms_messages" ON public.sms_messages
  FOR SELECT USING (org_id = public.current_user_org_id());
CREATE POLICY "org members write sms_messages" ON public.sms_messages
  FOR INSERT WITH CHECK (org_id = public.current_user_org_id());
CREATE POLICY "admins manage sms_messages" ON public.sms_messages
  FOR ALL USING (public.has_role(auth.uid(), 'admin'));

-- drip_sequences
CREATE POLICY "org members read drip_sequences" ON public.drip_sequences
  FOR SELECT USING (org_id = public.current_user_org_id());
CREATE POLICY "org members write drip_sequences" ON public.drip_sequences
  FOR INSERT WITH CHECK (org_id = public.current_user_org_id());
CREATE POLICY "org members update drip_sequences" ON public.drip_sequences
  FOR UPDATE USING (org_id = public.current_user_org_id());
CREATE POLICY "org members delete drip_sequences" ON public.drip_sequences
  FOR DELETE USING (org_id = public.current_user_org_id());

-- drip_steps (inherits org via sequence)
CREATE POLICY "org members read drip_steps" ON public.drip_steps
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.drip_sequences s WHERE s.id = sequence_id AND s.org_id = public.current_user_org_id())
  );
CREATE POLICY "org members write drip_steps" ON public.drip_steps
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.drip_sequences s WHERE s.id = sequence_id AND s.org_id = public.current_user_org_id())
  );
CREATE POLICY "org members update drip_steps" ON public.drip_steps
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.drip_sequences s WHERE s.id = sequence_id AND s.org_id = public.current_user_org_id())
  );
CREATE POLICY "org members delete drip_steps" ON public.drip_steps
  FOR DELETE USING (
    EXISTS (SELECT 1 FROM public.drip_sequences s WHERE s.id = sequence_id AND s.org_id = public.current_user_org_id())
  );

-- drip_enrollments
CREATE POLICY "org members read drip_enrollments" ON public.drip_enrollments
  FOR SELECT USING (org_id = public.current_user_org_id());
CREATE POLICY "org members write drip_enrollments" ON public.drip_enrollments
  FOR INSERT WITH CHECK (org_id = public.current_user_org_id());
CREATE POLICY "org members update drip_enrollments" ON public.drip_enrollments
  FOR UPDATE USING (org_id = public.current_user_org_id());

-- ----------------------------------------------------------------------------;

CREATE SCHEMA snap_relaunch;
    CREATE TABLE snap_relaunch.customer_source_acceptances(id uuid PRIMARY KEY,consumer_user_id uuid,valid_until timestamptz,revoked boolean DEFAULT false,mapping_ids uuid[] DEFAULT '{}',purpose text DEFAULT 'crm');
    CREATE TABLE snap_relaunch.customer_property_mappings(id uuid DEFAULT gen_random_uuid(),customer_property_id uuid,created_for_source boolean);
    CREATE TABLE snap_relaunch.source_crm_links(id uuid DEFAULT gen_random_uuid(),lead_id uuid,activity_id uuid,acceptance_id uuid,consumer_user_id uuid,org_id uuid);
    CREATE FUNCTION snap_relaunch.require_source_acceptance_v1(p_acceptance uuid,p_purpose text) RETURNS uuid LANGUAGE plpgsql STABLE SECURITY DEFINER AS $$ BEGIN
      IF NOT EXISTS(SELECT 1 FROM snap_relaunch.customer_source_acceptances a WHERE a.id=p_acceptance AND a.consumer_user_id=auth.uid() AND a.valid_until>now() AND NOT a.revoked) THEN
        RAISE EXCEPTION 'Source acceptance unavailable' USING ERRCODE='42501'; END IF; RETURN p_acceptance; END $$;

CREATE FUNCTION public.fn_is_source_property_v1(p_property_id uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$
 SELECT EXISTS(SELECT 1 FROM snap_relaunch.customer_property_mappings m WHERE m.customer_property_id=p_property_id AND m.created_for_source)
$$;
CREATE FUNCTION public.fn_source_property_visible_v1(p_property_id uuid)
RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE candidate record;a uuid;BEGIN
 IF auth.uid() IS NULL THEN RETURN false;END IF;
 IF NOT public.fn_is_source_property_v1(p_property_id) THEN RETURN true;END IF;
 FOR candidate IN SELECT DISTINCT ac.id,ac.purpose FROM snap_relaunch.customer_source_acceptances ac
  JOIN snap_relaunch.customer_property_mappings m ON m.id=ANY(ac.mapping_ids)
  WHERE ac.consumer_user_id=auth.uid() AND m.customer_property_id=p_property_id LOOP
  BEGIN
   a:=snap_relaunch.require_source_acceptance_v1(candidate.id,candidate.purpose);RETURN true;
  EXCEPTION WHEN SQLSTATE '42501' THEN NULL;
  END;
 END LOOP;
 RETURN false;
END $$;
CREATE FUNCTION public.fn_source_lead_visible_v1(p_lead_id uuid,p_property_id uuid DEFAULT NULL)
RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE link snap_relaunch.source_crm_links%ROWTYPE;a uuid;BEGIN
 IF auth.uid() IS NULL THEN RETURN false;END IF;
 IF NOT EXISTS(SELECT 1 FROM snap_relaunch.source_crm_links WHERE lead_id=p_lead_id) THEN
  RETURN NOT public.fn_is_source_property_v1(coalesce(p_property_id,(SELECT property_id FROM public.leads WHERE id=p_lead_id)));
 END IF;
 FOR link IN SELECT * FROM snap_relaunch.source_crm_links WHERE lead_id=p_lead_id AND consumer_user_id=auth.uid() LOOP
  BEGIN
   a:=snap_relaunch.require_source_acceptance_v1(link.acceptance_id,'crm');
   IF EXISTS(SELECT 1 FROM public.leads l JOIN public.profiles p ON p.user_id=auth.uid() WHERE l.id=link.lead_id
     AND l.created_by=auth.uid() AND l.org_id=link.org_id AND p.org_id=link.org_id) THEN RETURN true;END IF;
  EXCEPTION WHEN SQLSTATE '42501' THEN NULL;
  END;
 END LOOP;
 RETURN false;
END $$;
REVOKE ALL ON FUNCTION public.fn_is_source_property_v1(uuid),public.fn_source_property_visible_v1(uuid),public.fn_source_lead_visible_v1(uuid,uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.fn_is_source_property_v1(uuid),public.fn_source_property_visible_v1(uuid),public.fn_source_lead_visible_v1(uuid,uuid) TO authenticated,service_role;

CREATE POLICY source_property_account_fence_v1 ON public.properties AS RESTRICTIVE FOR ALL TO authenticated
 USING(public.fn_source_property_visible_v1(id)) WITH CHECK(public.fn_source_property_visible_v1(id));
CREATE POLICY source_lead_account_fence_v1 ON public.leads AS RESTRICTIVE FOR ALL TO authenticated
 USING(public.fn_source_lead_visible_v1(id,property_id)) WITH CHECK(public.fn_source_lead_visible_v1(id,property_id));
CREATE POLICY source_lead_activity_fence_v1 ON public.lead_activities AS RESTRICTIVE FOR ALL TO authenticated
 USING(public.fn_source_lead_visible_v1(lead_id)) WITH CHECK(public.fn_source_lead_visible_v1(lead_id));

CREATE FUNCTION public.protect_source_property_and_lead_v1() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
BEGIN
 IF TG_TABLE_NAME='properties' AND public.fn_is_source_property_v1(OLD.id) THEN
  RAISE EXCEPTION 'Mapped source property evidence is immutable; append a reviewed mapping revision' USING ERRCODE='42501';
 ELSIF TG_TABLE_NAME='leads' AND EXISTS(SELECT 1 FROM snap_relaunch.source_crm_links WHERE lead_id=OLD.id) THEN
  IF TG_OP='DELETE' OR NEW.property_id IS DISTINCT FROM OLD.property_id OR NEW.org_id IS DISTINCT FROM OLD.org_id
   OR NEW.created_by IS DISTINCT FROM OLD.created_by THEN
   RAISE EXCEPTION 'Source lead identity is immutable' USING ERRCODE='42501';END IF;
 ELSIF TG_TABLE_NAME='lead_activities' AND EXISTS(SELECT 1 FROM snap_relaunch.source_crm_links WHERE activity_id=OLD.id) THEN
  -- The linked annotation is part of the immutable acceptance receipt. Moving
  -- it to an ordinary shared-org lead would otherwise bypass the source fence.
  RAISE EXCEPTION 'Linked source activity is immutable; append a new activity' USING ERRCODE='42501';
 END IF;
 IF TG_OP='DELETE' THEN RETURN OLD;END IF;RETURN NEW;
END $$;

CREATE TRIGGER source_property_immutable_v1 BEFORE UPDATE OR DELETE ON public.properties FOR EACH ROW EXECUTE FUNCTION public.protect_source_property_and_lead_v1();
    CREATE TRIGGER source_lead_identity_v1 BEFORE UPDATE OR DELETE ON public.leads FOR EACH ROW EXECUTE FUNCTION public.protect_source_property_and_lead_v1();
    CREATE TRIGGER source_activity_immutable_v1 BEFORE UPDATE OR DELETE ON public.lead_activities FOR EACH ROW EXECUTE FUNCTION public.protect_source_property_and_lead_v1();

-- Create public.profiles on every new auth user so free_unlocks_remaining (default 3)
-- is always present, including when email confirmation prevents client-side inserts.

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.user_profiles (user_id, credits)
  VALUES (NEW.id, 10)
  ON CONFLICT (user_id) DO NOTHING;

  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, 'user')
  ON CONFLICT DO NOTHING;

  INSERT INTO public.profiles (user_id, org_id, email, full_name)
  VALUES (
    NEW.id,
    '00000000-0000-0000-0000-000000000001'::uuid,
    NEW.email,
    NULLIF(btrim(COALESCE(NEW.raw_user_meta_data->>'full_name', '')), '')
  )
  ON CONFLICT (user_id) DO NOTHING;

  RETURN NEW;
END;
$$;

-- Backfill: auth users missing a profiles row (one-time; preserves existing rows)
INSERT INTO public.profiles (user_id, org_id, email, full_name)
SELECT
  au.id,
  '00000000-0000-0000-0000-000000000001'::uuid,
  au.email,
  NULLIF(btrim(COALESCE(au.raw_user_meta_data->>'full_name', '')), '')
FROM auth.users au
WHERE NOT EXISTS (SELECT 1 FROM public.profiles p WHERE p.user_id = au.id)
ON CONFLICT (user_id) DO NOTHING;

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
    GRANT USAGE ON SCHEMA public TO anon,authenticated,service_role;
    GRANT ALL ON ALL TABLES IN SCHEMA public TO anon,authenticated,service_role;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon,authenticated,service_role;
    CREATE POLICY roles_admin_insert ON public.user_roles FOR INSERT TO authenticated WITH CHECK(public.has_role(auth.uid(),'admin'));
    CREATE POLICY roles_admin_update ON public.user_roles FOR UPDATE TO authenticated USING(public.has_role(auth.uid(),'admin'));
    CREATE POLICY roles_admin_delete ON public.user_roles FOR DELETE TO authenticated USING(public.has_role(auth.uid(),'admin'));
    REVOKE ALL ON public.profiles,public.user_profiles FROM anon;
    ALTER POLICY "Users can insert their own profile" ON public.profiles TO authenticated WITH CHECK(public.has_role(auth.uid(),'admin'));
    ALTER POLICY "Users can update their own profile" ON public.profiles TO authenticated USING(public.has_role(auth.uid(),'admin')) WITH CHECK(public.has_role(auth.uid(),'admin'));

CREATE TABLE public."subscription_plans" ("id" uuid DEFAULT gen_random_uuid() NOT NULL,"name" text NOT NULL,"display_name" text NOT NULL,"description" text,"price_monthly_cents" integer DEFAULT 0 NOT NULL,"price_annual_cents" integer DEFAULT 0 NOT NULL,"max_monthly_exports" integer DEFAULT 0 NOT NULL,"max_counties" integer DEFAULT 0 NOT NULL,"max_user_seats" integer DEFAULT 1 NOT NULL,"max_skip_traces_per_month" integer DEFAULT 0 NOT NULL,"features" jsonb DEFAULT '[]'::jsonb,"has_advanced_filters" boolean DEFAULT false NOT NULL,"has_violation_filtering" boolean DEFAULT false NOT NULL,"has_rolling_intelligence" boolean DEFAULT false NOT NULL,"has_escalation_alerts" boolean DEFAULT false NOT NULL,"has_api_access" boolean DEFAULT false NOT NULL,"has_dedicated_manager" boolean DEFAULT false NOT NULL,"sort_order" integer DEFAULT 0 NOT NULL,"is_active" boolean DEFAULT true NOT NULL,"created_at" timestamp with time zone DEFAULT now() NOT NULL,"updated_at" timestamp with time zone DEFAULT now() NOT NULL,"max_states" integer DEFAULT 5,"data_tier" text DEFAULT 'basic'::text NOT NULL,"stripe_price_id" text);

ALTER TABLE public."subscription_plans" ADD CONSTRAINT "subscription_plans_name_key" UNIQUE (name);

ALTER TABLE public."subscription_plans" ADD CONSTRAINT "subscription_plans_pkey" PRIMARY KEY (id);

ALTER TABLE public."subscription_plans" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view active plans" ON public."subscription_plans" FOR SELECT TO "public" USING ((is_active = true));

CREATE TABLE public."user_subscriptions" ("id" uuid DEFAULT gen_random_uuid() NOT NULL,"user_id" uuid NOT NULL,"plan_id" uuid NOT NULL,"stripe_customer_id" text,"stripe_subscription_id" text,"status" text DEFAULT 'active'::text NOT NULL,"current_period_start" timestamp with time zone,"current_period_end" timestamp with time zone,"cancel_at" timestamp with time zone,"cancelled_at" timestamp with time zone,"created_at" timestamp with time zone DEFAULT now() NOT NULL,"updated_at" timestamp with time zone DEFAULT now() NOT NULL,"trial_started_at" timestamp with time zone,"trial_ends_at" timestamp with time zone,"trial_tier" text,"trial_exports_used" integer DEFAULT 0,"trial_exports_limit" integer DEFAULT 50);

ALTER TABLE public."user_subscriptions" ADD CONSTRAINT "chk_trial_tier" CHECK (((trial_tier IS NULL) OR (trial_tier = ANY (ARRAY['starter'::text, 'professional'::text, 'enterprise'::text]))));

ALTER TABLE public."user_subscriptions" ADD CONSTRAINT "user_subscriptions_pkey" PRIMARY KEY (id);

ALTER TABLE public."user_subscriptions" ADD CONSTRAINT "user_subscriptions_plan_id_fkey" FOREIGN KEY (plan_id) REFERENCES subscription_plans(id) ON DELETE RESTRICT;

ALTER TABLE public."user_subscriptions" ADD CONSTRAINT "user_subscriptions_status_check" CHECK ((status = ANY (ARRAY['active'::text, 'past_due'::text, 'cancelled'::text, 'unpaid'::text, 'trialing'::text])));

ALTER TABLE public."user_subscriptions" ADD CONSTRAINT "user_subscriptions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX idx_user_subscriptions_plan_id ON public.user_subscriptions USING btree (plan_id);

CREATE INDEX idx_user_subscriptions_status ON public.user_subscriptions USING btree (status);

CREATE INDEX idx_user_subscriptions_stripe_sub ON public.user_subscriptions USING btree (stripe_subscription_id);

CREATE INDEX idx_user_subscriptions_user_id ON public.user_subscriptions USING btree (user_id);

CREATE UNIQUE INDEX one_active_subscription_per_user ON public.user_subscriptions USING btree (user_id) WHERE (status = ANY (ARRAY['active'::text, 'trialing'::text, 'past_due'::text]));

CREATE UNIQUE INDEX unique_active_subscription_per_user ON public.user_subscriptions USING btree (user_id) WHERE (status = ANY (ARRAY['active'::text, 'trialing'::text, 'past_due'::text]));

CREATE UNIQUE INDEX unique_non_cancelled_subscription ON public.user_subscriptions USING btree (user_id) WHERE (status <> 'cancelled'::text);

ALTER TABLE public."user_subscriptions" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role manages subscriptions" ON public."user_subscriptions" FOR ALL TO "public" USING (((auth.jwt() ->> 'role'::text) = 'service_role'::text)) WITH CHECK (((auth.jwt() ->> 'role'::text) = 'service_role'::text));

CREATE POLICY "Users can view their own subscriptions" ON public."user_subscriptions" FOR SELECT TO "public" USING ((user_id = auth.uid()));

CREATE OR REPLACE FUNCTION public.update_subscription_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

CREATE TRIGGER update_subscription_plans_timestamp BEFORE UPDATE ON public.subscription_plans FOR EACH ROW EXECUTE FUNCTION update_subscription_timestamp();

CREATE TRIGGER update_user_subscriptions_timestamp BEFORE UPDATE ON public.user_subscriptions FOR EACH ROW EXECUTE FUNCTION update_subscription_timestamp();

CREATE TABLE IF NOT EXISTS public.credit_ledger (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid NOT NULL,
  delta       integer NOT NULL,
  reason      text NOT NULL,
  meta        jsonb,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.credit_ledger ENABLE ROW LEVEL SECURITY;

CREATE POLICY credit_ledger_user
  ON public.credit_ledger FOR SELECT TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY credit_ledger_insert
  ON public.credit_ledger FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

-- Helper view: current credit balance
CREATE OR REPLACE VIEW public.v_user_credits AS
SELECT user_id, COALESCE(SUM(delta), 0) AS balance
FROM public.credit_ledger
GROUP BY user_id;

-- Add computed columns for unique constraint on credit_ledger
ALTER TABLE credit_ledger 
ADD COLUMN IF NOT EXISTS job_id_extracted uuid GENERATED ALWAYS AS ((meta->>'job_id')::uuid) STORED,
ADD COLUMN IF NOT EXISTS property_id_extracted uuid GENERATED ALWAYS AS ((meta->>'property_id')::uuid) STORED;

-- Create unique index to prevent double refunds
CREATE UNIQUE INDEX IF NOT EXISTS uniq_ledger_job_prop_reason 
ON credit_ledger(user_id, job_id_extracted, property_id_extracted, reason)
WHERE job_id_extracted IS NOT NULL AND property_id_extracted IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_credit_ledger_unique_session 
ON public.credit_ledger ((meta->>'stripe_session_id'))
WHERE meta->>'stripe_session_id' IS NOT NULL;

-- Finding 23: Drop the dangerous INSERT policy on credit_ledger
-- Only SECURITY DEFINER functions (service role) should write to this table
DROP POLICY IF EXISTS "credit_ledger_insert" ON public.credit_ledger;

CREATE OR REPLACE FUNCTION public.guard_credit_ledger_debit_v1()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $function$
DECLARE v_balance bigint;
BEGIN
  IF TG_OP='UPDATE' THEN
    IF NEW.user_id IS DISTINCT FROM OLD.user_id OR NEW.delta IS DISTINCT FROM OLD.delta THEN
      RAISE EXCEPTION 'Credit ledger accounting entries are immutable' USING ERRCODE='42501';
    END IF;
    RETURN NEW;
  END IF;
  IF NEW.delta < 0 THEN
    PERFORM 1 FROM public.profiles WHERE user_id=NEW.user_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Credit account unavailable' USING ERRCODE='42501'; END IF;
    SELECT COALESCE(sum(delta),0) INTO v_balance FROM public.credit_ledger WHERE user_id=NEW.user_id;
    IF v_balance < -(NEW.delta::bigint) THEN
      RAISE EXCEPTION 'INSUFFICIENT_CREDITS' USING ERRCODE='P0001';
    END IF;
  END IF;
  RETURN NEW;
END;
$function$;
REVOKE ALL ON FUNCTION public.guard_credit_ledger_debit_v1() FROM PUBLIC,anon,authenticated;
CREATE TRIGGER credit_ledger_debit_guard_v1 BEFORE INSERT OR UPDATE OF user_id,delta ON public.credit_ledger
FOR EACH ROW EXECUTE FUNCTION public.guard_credit_ledger_debit_v1();

-- 5. Create transactions table
CREATE TABLE IF NOT EXISTS public.transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  stripe_payment_intent_id TEXT UNIQUE,
  amount INTEGER NOT NULL,
  currency TEXT NOT NULL DEFAULT 'usd',
  description TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'succeeded', 'failed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_transactions_user ON public.transactions(user_id);

ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own transactions"
  ON public.transactions FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

-- 6. Create affiliate_referrals table
CREATE TABLE IF NOT EXISTS public.affiliate_referrals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  referrer_id UUID NOT NULL,
  referred_user_id UUID NOT NULL UNIQUE,
  signup_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  first_purchase_at TIMESTAMPTZ,
  commission_paid BOOLEAN NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS idx_affiliate_referrals_referrer ON public.affiliate_referrals(referrer_id);

ALTER TABLE public.affiliate_referrals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own referrals"
  ON public.affiliate_referrals FOR SELECT
  TO authenticated
  USING (referrer_id = auth.uid());

-- 7. Create affiliate_commissions table
CREATE TABLE IF NOT EXISTS public.affiliate_commissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  referral_id UUID NOT NULL REFERENCES public.affiliate_referrals(id) ON DELETE CASCADE,
  transaction_id UUID NOT NULL REFERENCES public.transactions(id) ON DELETE CASCADE,
  amount INTEGER NOT NULL,
  commission_rate INTEGER NOT NULL DEFAULT 30,
  paid_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'cancelled'))
);

ALTER TABLE public.affiliate_commissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own commissions"
  ON public.affiliate_commissions FOR SELECT
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.affiliate_referrals ar
    WHERE ar.id = affiliate_commissions.referral_id
    AND ar.referrer_id = auth.uid()
  ));

-- =========================================================
-- Part 3: Webhook Events Table for Idempotency
-- =========================================================

CREATE TABLE IF NOT EXISTS public.webhook_events (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id text UNIQUE NOT NULL,
    event_type text NOT NULL,
    processed_at timestamptz NOT NULL DEFAULT now(),
    payload jsonb
);

ALTER TABLE public.webhook_events ENABLE ROW LEVEL SECURITY;

-- Only service role can access
CREATE POLICY "Service role only" ON public.webhook_events
FOR ALL USING (false) WITH CHECK (false);

CREATE INDEX IF NOT EXISTS idx_webhook_events_event_id ON public.webhook_events(event_id);
CREATE INDEX IF NOT EXISTS idx_webhook_events_processed_at ON public.webhook_events(processed_at);

GRANT INSERT, SELECT ON public.webhook_events TO service_role;

GRANT ALL ON public.subscription_plans,public.user_subscriptions,public.credit_ledger,
    public.transactions,public.affiliate_referrals,public.affiliate_commissions TO anon,authenticated,service_role;

CREATE TABLE public.subscription_usage ("api_calls_count" integer DEFAULT 0 NOT NULL,"created_at" timestamp with time zone DEFAULT now() NOT NULL,"exports_count" integer DEFAULT 0 NOT NULL,"id" uuid DEFAULT gen_random_uuid() NOT NULL,"period_end" date NOT NULL,"period_start" date NOT NULL,"skip_traces_count" integer DEFAULT 0 NOT NULL,"updated_at" timestamp with time zone DEFAULT now() NOT NULL,"user_id" uuid NOT NULL);

ALTER TABLE public.subscription_usage ADD CONSTRAINT "subscription_usage_pkey" PRIMARY KEY (id);

ALTER TABLE public.subscription_usage ADD CONSTRAINT "subscription_usage_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.subscription_usage ADD CONSTRAINT "unique_user_period" UNIQUE (user_id, period_start);

CREATE FUNCTION snap_relaunch.current_customer_subscription_v1(p_user_id uuid)
RETURNS SETOF public.user_subscriptions
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $fn$
 SELECT s.* FROM (
  SELECT us.* FROM public.user_subscriptions us WHERE us.user_id=p_user_id
  ORDER BY us.created_at DESC,us.id DESC LIMIT 1
 ) s
 WHERE auth.uid() IS NOT NULL AND p_user_id=auth.uid()
 AND EXISTS (SELECT 1 FROM auth.users u WHERE u.id=auth.uid()
  AND u.deleted_at IS NULL AND NOT coalesce(u.is_anonymous,false)
  AND (u.banned_until IS NULL OR u.banned_until<=now())
  AND (u.email_confirmed_at IS NOT NULL OR u.phone_confirmed_at IS NOT NULL))
 AND ((s.status='active' AND s.current_period_start<=now() AND s.current_period_end>now())
   OR (s.status IN ('trial','trialing') AND s.trial_started_at<=now() AND s.trial_ends_at>now()));
$fn$;
REVOKE ALL ON FUNCTION snap_relaunch.current_customer_subscription_v1(uuid) FROM PUBLIC,anon,authenticated,service_role;
-- New helper only: do not inherit direct EXECUTE from namespace/global default ACLs.
-- Existing public wrappers execute as their trusted owner; platform defaults elsewhere are unchanged.
DO $private_acl$ DECLARE grantee_name text; BEGIN
 FOR grantee_name IN SELECT DISTINCT pg_get_userbyid(a.grantee)
  FROM pg_proc p CROSS JOIN LATERAL aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a
  WHERE p.oid='snap_relaunch.current_customer_subscription_v1(uuid)'::regprocedure
    AND a.grantee<>0 AND a.grantee<>p.proowner
 LOOP EXECUTE format('REVOKE ALL ON FUNCTION snap_relaunch.current_customer_subscription_v1(uuid) FROM %I',grantee_name); END LOOP;
END $private_acl$;


CREATE OR REPLACE FUNCTION public.fn_get_user_subscription(p_user_id uuid DEFAULT auth.uid())
 RETURNS TABLE(subscription_id uuid, user_id uuid, plan_id uuid, plan_name text, display_name text, status text, current_period_start timestamp with time zone, current_period_end timestamp with time zone, max_monthly_exports integer, max_counties integer, max_user_seats integer, max_skip_traces_per_month integer, has_advanced_filters boolean, has_violation_filtering boolean, has_rolling_intelligence boolean, has_escalation_alerts boolean, has_api_access boolean, stripe_subscription_id text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT
    s.id as subscription_id,
    s.user_id,
    s.plan_id,
    p.name as plan_name,
    p.display_name,
    s.status,
    s.current_period_start,
    s.current_period_end,
    p.max_monthly_exports,
    p.max_counties,
    p.max_user_seats,
    p.max_skip_traces_per_month,
    p.has_advanced_filters,
    p.has_violation_filtering,
    p.has_rolling_intelligence,
    p.has_escalation_alerts,
    p.has_api_access,
    s.stripe_subscription_id
  FROM snap_relaunch.current_customer_subscription_v1(p_user_id) s
  JOIN public.subscription_plans p ON s.plan_id = p.id
  ;
$function$
;

CREATE OR REPLACE FUNCTION public.fn_get_current_usage(p_user_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE s public.user_subscriptions%ROWTYPE; v_exports integer:=0; v_api integer:=0; v_start timestamptz;v_end timestamptz;
BEGIN
 IF auth.uid() IS NULL OR p_user_id IS DISTINCT FROM auth.uid() THEN
  RAISE EXCEPTION 'Account access denied' USING ERRCODE='42501';END IF;
 SELECT * INTO s FROM snap_relaunch.current_customer_subscription_v1(p_user_id);
 IF NOT FOUND THEN
  RETURN jsonb_build_object('exports_count',0,'api_calls_count',0,'period_start',NULL,'period_end',NULL);
 END IF;
 IF s.status IN ('trial','trialing') THEN
  v_start:=s.trial_started_at;v_end:=s.trial_ends_at;
  v_exports:=coalesce(s.trial_exports_used,0);
 ELSE
  v_start:=s.current_period_start;v_end:=s.current_period_end;
  SELECT coalesce(exports_count,0),coalesce(api_calls_count,0) INTO v_exports,v_api
  FROM public.subscription_usage WHERE user_id=p_user_id AND period_start=v_start::date;
 END IF;
 RETURN jsonb_build_object('exports_count',coalesce(v_exports,0),'api_calls_count',coalesce(v_api,0),
  'period_start',v_start,'period_end',v_end);
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_check_subscription_limit(p_usage_type text, p_amount integer DEFAULT 1, p_user_id uuid DEFAULT auth.uid())
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE s public.user_subscriptions%ROWTYPE; p public.subscription_plans%ROWTYPE;
 v_limit integer; v_current integer;v_usage jsonb;
BEGIN
 IF auth.uid() IS NULL OR p_user_id IS DISTINCT FROM auth.uid() THEN
  RAISE EXCEPTION 'Account access denied' USING ERRCODE='42501';END IF;
 IF p_amount IS NULL OR p_amount<=0 THEN RETURN jsonb_build_object('allowed',false,'reason','invalid_amount');END IF;
 SELECT * INTO s FROM snap_relaunch.current_customer_subscription_v1(p_user_id);
 IF NOT FOUND THEN RETURN jsonb_build_object('allowed',false,'reason','no_current_subscription',
  'message','A current verified subscription or trial is required.');END IF;
 IF p_usage_type IS DISTINCT FROM 'exports' THEN
  RETURN jsonb_build_object('allowed',false,'reason','unsupported_usage',
   'message','This usage path has no supported reservation.');END IF;
 SELECT * INTO p FROM public.subscription_plans WHERE id=s.plan_id;
 IF NOT FOUND THEN RETURN jsonb_build_object('allowed',false,'reason','plan_unavailable');END IF;
 IF s.status IN ('trial','trialing') THEN
  v_limit:=s.trial_exports_limit;v_current:=coalesce(s.trial_exports_used,0);
 ELSE
  v_limit:=p.max_monthly_exports;v_usage:=public.fn_get_current_usage(p_user_id);
  v_current:=(v_usage->>'exports_count')::integer;
 END IF;
 IF v_current IS NULL OR v_current<0 OR v_limit IS NULL OR v_limit < -1
  OR (s.status IN ('trial','trialing') AND v_limit<0) THEN
  RETURN jsonb_build_object('allowed',false,'reason','usage_unverified');END IF;
 IF v_limit=-1 THEN RETURN jsonb_build_object('allowed',true,'current',v_current,'limit',NULL,
  'remaining',NULL,'plan_name',p.name,'unlimited',true);END IF;
 RETURN jsonb_build_object('allowed',v_current::bigint+p_amount::bigint<=v_limit::bigint,
  'reason',CASE WHEN v_current::bigint+p_amount::bigint<=v_limit::bigint THEN 'within_limit' ELSE 'limit_exceeded' END,
  'current',v_current,'limit',v_limit,'remaining',greatest(0::bigint,v_limit::bigint-v_current::bigint-p_amount::bigint),
  'plan_name',p.name,'message','The allowance check does not reserve or execute an export.');
END;
$function$;

CREATE OR REPLACE FUNCTION public.fn_get_trial_status(p_user_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE s public.user_subscriptions%ROWTYPE;current_entitlement boolean:=false;is_trial boolean:=false;
 empty_result jsonb:=jsonb_build_object('is_on_trial',false,'has_trial_expired',false,'has_active_subscription',false,
 'trial_days_remaining',0,'trial_exports_used',0,'trial_exports_remaining',0,'trial_exports_limit',0,
 'trial_tier',NULL,'trial_ends_at',NULL,'trial_started_at',NULL,'subscription_status',NULL,'can_export',false,'plan_id',NULL);
BEGIN
 IF auth.uid() IS NULL OR p_user_id IS DISTINCT FROM auth.uid() THEN
  RAISE EXCEPTION 'Account access denied' USING ERRCODE='42501';END IF;
 IF NOT EXISTS(SELECT 1 FROM auth.users u WHERE u.id=auth.uid() AND u.deleted_at IS NULL
  AND NOT coalesce(u.is_anonymous,false) AND (u.banned_until IS NULL OR u.banned_until<=now())
  AND (u.email_confirmed_at IS NOT NULL OR u.phone_confirmed_at IS NOT NULL)) THEN RETURN empty_result;END IF;
 SELECT * INTO s FROM public.user_subscriptions WHERE user_id=p_user_id ORDER BY created_at DESC,id DESC LIMIT 1;
 IF NOT FOUND THEN RETURN empty_result;END IF;
 current_entitlement:=EXISTS(SELECT 1 FROM snap_relaunch.current_customer_subscription_v1(p_user_id));
 is_trial:=s.status IN ('trial','trialing');
 RETURN jsonb_build_object('is_on_trial',is_trial AND current_entitlement,
  'has_trial_expired',is_trial AND s.trial_ends_at IS NOT NULL AND s.trial_ends_at<=now(),
  'has_active_subscription',s.status='active' AND current_entitlement,
  'trial_days_remaining',CASE WHEN is_trial AND current_entitlement THEN round(extract(epoch FROM(s.trial_ends_at-now()))/86400.0,1) ELSE 0 END,
  'trial_exports_used',coalesce(s.trial_exports_used,0),
  'trial_exports_remaining',CASE WHEN is_trial AND current_entitlement AND s.trial_exports_limit>=0 AND coalesce(s.trial_exports_used,0)>=0
    THEN greatest(0::bigint,s.trial_exports_limit::bigint-coalesce(s.trial_exports_used,0)::bigint) ELSE 0 END,
  'trial_exports_limit',greatest(0,coalesce(s.trial_exports_limit,0)),
  'trial_tier',s.trial_tier,'trial_ends_at',s.trial_ends_at,'trial_started_at',s.trial_started_at,
  'subscription_status',s.status,'plan_id',s.plan_id,
  'can_export',current_entitlement AND coalesce((public.fn_check_subscription_limit('exports',1,p_user_id)->>'allowed')::boolean,false));
END;
$function$;


-- Close all application access until candidate migrations and final hardening finish.
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC,anon,authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC,anon,authenticated;
REVOKE ALL ON SCHEMA snap_relaunch FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON ALL TABLES IN SCHEMA snap_relaunch FROM PUBLIC,anon,authenticated,service_role;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA snap_relaunch FROM PUBLIC,anon,authenticated,service_role;
COMMIT;
