/** Offline SQL generation only. Never reads credentials or connects to a database. */
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFile,writeFile} from 'node:fs/promises';
import {createTenancyDb} from '../../../tests/helpers/tenancy-db.mjs';
import {billingBaseline} from '../../../tests/helpers/billing-db.mjs';

const here=new URL('./',import.meta.url),root=new URL('../../../',import.meta.url);
const hash=value=>createHash('sha256').update(value).digest('hex');
const read=path=>readFile(new URL(path,root),'utf8');
const migrations=[
  '20260924182954_snap_customer_workspace_isolation_v1.sql',
  '20260924183006_snap_billing_atomic_fulfillment_v1.sql',
  '20260924183021_snap_crm_workflow_v1.sql',
  '20260924214048_snap_crm_outcome_conflict_v1.sql',
];
const inputs=['tests/helpers/tenancy-db.mjs','tests/helpers/billing-db.mjs',
  'scripts/tests/release-stage/native-catalog-20260924.json',
  'supabase/migrations/20260915030704_87a8db45-8e67-4add-825a-0a86de81af73.sql',
  ...migrations.map(name=>`supabase/migrations/${name}`)];
for(const helper of inputs.slice(0,2))for(const match of (await read(helper)).matchAll(/\b\d{14}_[a-z0-9_-]+\.sql\b/g)){
  const path=`supabase/migrations/${match[0]}`;if(!inputs.includes(path))inputs.push(path);
}
inputs.push('scripts/tests/release-hosted/generate.mjs','scripts/tests/release-hosted/preflight.sql','scripts/tests/release-hosted/hardening.sql',
  'scripts/tests/release-hosted/05_function_search_paths.sql','scripts/tests/release-hosted/06_self_scoped_role_check.sql');
const chunks=[];let removed=0;
const adapter={exec:async value=>{
  let sql=value;
  if(sql.trimStart().startsWith('CREATE ROLE anon NOLOGIN;')){
    assert.equal(removed++,0);
    const boundary=sql.indexOf('CREATE TYPE public.app_role');assert.ok(boundary>0);
    assert.equal(hash(sql.slice(0,boundary)),'d677213398ffd082790bca183d37491595c2286e8ee35170f45f7379e45d0aea','Managed fixture prefix changed');
    sql=sql.slice(boundary);
  }
  assert.doesNotMatch(sql,/\b(?:CREATE|DROP|ALTER)\s+(?:OR\s+REPLACE\s+)?(?:ROLE\b|SCHEMA\s+auth\b|TABLE\s+auth\.|FUNCTION\s+auth\.|PUBLICATION\b)/i,'Managed object replacement forbidden');
  assert.doesNotMatch(sql,/\b(?:cron\.schedule|net\.http_|vault\.|dblink\b)/i,'External work forbidden');
  chunks.push(sql.trim().replace(/;?$/,';'));
}};
await createTenancyDb({applyMigration:false,database:adapter});
await billingBaseline(adapter);assert.equal(removed,1);

// Copy only current, account-scoped read helpers. The historical migration's
// production-specific preflight, other functions, data and ACL capture are not replayed.
const reads=await read(inputs[3]);
const expected=JSON.parse(reads.match(/\$expected\$([\s\S]*?)\$expected\$::jsonb/)?.[1]??'null');
assert.ok(expected?.usage_columns?.length>5&&expected.usage_constraints?.length===3);
const quote=value=>`"${value.replaceAll('"','""')}"`;
chunks.push(`CREATE TABLE public.subscription_usage (${expected.usage_columns.map(c=>`${quote(c.name)} ${c.type}${c.default===null?'':` DEFAULT ${c.default}`}${c.notnull?' NOT NULL':''}`).join(',')});`);
for(const c of expected.usage_constraints)chunks.push(`ALTER TABLE public.subscription_usage ADD CONSTRAINT ${quote(c.name)} ${c.definition};`);
const start=reads.indexOf('CREATE FUNCTION snap_relaunch.current_customer_subscription_v1(');
const end=reads.indexOf('CREATE OR REPLACE FUNCTION public.fn_check_county_limit(',start);
assert.ok(start>0&&end>start);chunks.push(reads.slice(start,end));

const preflight=await readFile(new URL('preflight.sql',here),'utf8');
const hardening=await readFile(new URL('hardening.sql',here),'utf8');
const baseline=`-- GENERATED by scripts/tests/release-hosted/generate.mjs; synthetic blank staging ONLY.\n-- Apply the three unchanged candidate migrations, then 04_hardening.sql before creating accounts.\nBEGIN;\nSET LOCAL lock_timeout='5s';\nSET LOCAL statement_timeout='60s';\n${preflight}\n${chunks.join('\n\n')}\n-- Close all application access until candidate migrations and final hardening finish.\nREVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC,anon,authenticated;\nREVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC,anon,authenticated;\nREVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC,anon,authenticated;\nREVOKE ALL ON SCHEMA snap_relaunch FROM PUBLIC,anon,authenticated,service_role;\nREVOKE ALL ON ALL TABLES IN SCHEMA snap_relaunch FROM PUBLIC,anon,authenticated,service_role;\nREVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA snap_relaunch FROM PUBLIC,anon,authenticated,service_role;\nCOMMIT;\n`;
for(const sql of [baseline,hardening])assert.doesNotMatch(sql,/https:\/\/[a-z0-9]{20}\.supabase\.(?:co|in)|sk_(?:live|test)_|service_role_key|@[^\s'"]+\.[a-z]{2,}/i,'Private target, credentials or account data forbidden');
const outputs=[['00_baseline.sql',baseline],['04_hardening.sql',hardening]];
for(const [name,sql] of outputs)await writeFile(new URL(name,here),sql);
const bootstrapOrder=['scripts/tests/release-hosted/00_baseline.sql',...migrations.slice(0,3).map(name=>`supabase/migrations/${name}`),'scripts/tests/release-hosted/04_hardening.sql'];
const additiveOrder=['scripts/tests/release-hosted/05_function_search_paths.sql','scripts/tests/release-hosted/06_self_scoped_role_check.sql',`supabase/migrations/${migrations[3]}`];
const manifest={kind:'snap_hosted_synthetic_sql',schema_version:1,remote_operations:0,
  apply_order:[...bootstrapOrder,...additiveOrder],bootstrap_apply_order:bootstrapOrder,additive_apply_order:additiveOrder,
  inputs:await Promise.all(inputs.map(async path=>({path,sha256:hash(await read(path))}))),
  outputs:outputs.map(([name,sql])=>({path:`scripts/tests/release-hosted/${name}`,sha256:hash(sql),bytes:Buffer.byteLength(sql)})),
  limits:['Selected synthetic schema, not a production clone','Managed Auth and realtime definitions preserved; signup trigger is application-owned','Source acceptance and mapping are limited fixtures; source detail/export remain held','No provider credentials, scheduled jobs, production data, or paid features']};
await writeFile(new URL('manifest.json',here),JSON.stringify(manifest,null,2)+'\n');
console.log(JSON.stringify(manifest.outputs));
