import React from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { Settings } from '../src/pages/Settings';
import { FixtureAuthProvider } from './checkout-return-fixture';
const client=new QueryClient({defaultOptions:{queries:{retry:false,refetchOnWindowFocus:false}}});
client.setQueryData(['credits','balance'],999999);
client.setQueryData(['subscription','00000000-0000-4000-8000-000000000001'],{plan_name:'professional'});
createRoot(document.getElementById('root')!).render(<FixtureAuthProvider><QueryClientProvider client={client}><BrowserRouter><Settings/></BrowserRouter></QueryClientProvider></FixtureAuthProvider>);
